### ISSUE TITLE
Improve project name

### ISSUE THREAD

**Issue by daudix-UFO** [ArtyIF/AdwCustomizer#1]
Привет, во первых я хотел бы отметить редкость этой ситуации, вам, русскому пользователю линукс, рабочего стола GNOME, пришла такая-же идея как и мне неделю-две назад

![Снимок экрана от 2022-07-18 23-36-03-obfuscated](https://user-images.githubusercontent.com/77155297/179613511-4fa2713f-31ff-49ab-bcd4-be9dcab1d621.png)

Но, раз уж я не успел, я бы хотел помочь с тим проектом, я начну работу над иконкой, а также сделаю некоторые Mock-up'ы интерфейса (если вы согласны)

По-поводу имени для проекта, согласно [GNOME HIG](https://developer.gnome.org/hig/guidelines/app-naming.html), имя не должно быть словом которое сделано из других слов, поэтому я предлогаю другое имя:

### Adwaita Lab

_Также, если вы захотите, у меня есть некоторые интересные идеи для этого проекта ;)_

**Comment by ArtyIF** [comment]
Да, я согласен насчёт Вашей помощи. Форкайте проект, потом делайте пуш-реквест.

Насчёт имени проекта - я подумаю. Дело в том, что AdwCustomizer придётся в любом случае оставить как кодовое имя (например, как GNOME Files до сих пор запускается командой nautilus). По мне, Adwaita Manager очень даже звучит.

**Comment by ArtyIF** [comment]
Fixed in 9e5b093c07fc5ffd3bc621dec7c450e40b6a3a84
