### ISSUE TITLE
KeyError: 'XDG_CONFIG_HOME'

### ISSUE THREAD

**Issue by darkblaze69** [ArtyIF/AdwCustomizer#34]
I have not set XDG_CONFIG_HOME environmental so it won't launch.

```
Traceback (most recent call last):
  File "/usr/share/adwcustomizer/adwcustomizer/main.py", line 120, in do_activate
    preset_directory = os.path.join(os.environ['XDG_CONFIG_HOME'], "presets")
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_CONFIG_HOME'
```

**Comment by ArtyIF** [comment]
That's weird, Flatpak is supposed to set that for you. What's your OS?

**Comment by darkblaze69** [comment]
running on Manjaro, AUR with libadwaita-git 1.2-alpha without Flatpak

**Comment by ArtyIF** [comment]
That might be the issue. It's designed to be a Flatpak package. There's a guide on installing this package as a flatpak in readme.

**Comment by ArtyIF** [comment]
Also it's weird that that wasn't set, Flatpak or not. It's usually defined. What DE do you use?

**Comment by darkblaze69** [comment]
GNOME

**Comment by ArtyIF** [comment]
Has installing Adwaita Manager as Flatpak helped?

**Comment by ArtyIF** [comment]
Any updates on the issue? If it's not fixed yet, reopen the issue or tell me to reopen the issue if you can't do it yourself.
