### ISSUE TITLE
Segmentation fault on launch

### ISSUE THREAD

**Issue by EntityinArray** [ArtyIF/AdwCustomizer#69]
Good day, thank you for working on this amazing project.
I recently updated Python to 3.10.5 and now AdwCustomizer just crashes with segfault.
```
[entityinarray@asuspc ~]$ python --version
Python 3.10.5
[entityinarray@asuspc ~]$ flatpak run --devel --command=sh com.github.ArtyIF.AdwCustomizer 
[📦 com.github.ArtyIF.AdwCustomizer ~]$ /app/bin/
adwcustomizer       blueprint-compiler  
[📦 com.github.ArtyIF.AdwCustomizer ~]$ /app/bin/adwcustomizer 
Segmentation fault (core dumped)
```

I'm not very tech-savvy with debugging Flatpak apps, please tell me what I need to do, in order to provide more information.
Thanks!

**Comment by ArtyIF** [comment]
Try using `flatpak run com.github.ArtyIF.AdwCustomizer` instead.

**Comment by EntityinArray** [comment]
Same thing, but it doesn't even write anything back into stdout. Just exits immideately and doesn't start. I tried 
removing everything and doing flatpak-builder from master and still face the same issue

**Comment by ArtyIF** [comment]
Pull the repository and try again. Also make sure your current directory is the repository root.

**Comment by EntityinArray** [comment]
Ok, thanks. I will try it when i'm back home

**Comment by EntityinArray** [comment]
rm -rf'd the local git repository and cloned everything from scratch, built as per instructions and still won't run

**Comment by ArtyIF** [comment]
I can't replicate the bug, unfortunately. Could you please name your PC's specs and versions of programs (distro, kernel, Flatpak, desktop environment etc.) you're using?

**Comment by ArtyIF** [comment]
Actually, can you open the cloned project in GNOME Builder and building it there? What does it say when you run it like that?

**Comment by EntityinArray** [comment]
Hey, sorry for not responding:
```
CPU: Intel Core i3-4160
GPU: Intel HD Graphics 4400
OS: Arch Linux
Kernel: Linux 5.18.16-arch1-1
Flatpak: 1.12.7
DE: GNOME Wayland
```

Gonna try build the project in the GNOME Builder

**Comment by EntityinArray** [comment]
Downloaded gnome-builder from flatpak, it won't build and shows this error:
```
flatpak-builder --arch=x86_64 --ccache --force-clean --disable-updates --disable-download --state-dir /home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder --stop-at=adwcustomizer /home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/projects/AdwCustomizer/flatpak/staging/x86_64-main /home/entityinarray/Compiles/AdwCustomizer/com.github.ArtyIF.AdwCustomizer.json
Emptying app dir '/home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/projects/AdwCustomizer/flatpak/staging/x86_64-main'
Starting build of com.github.ArtyIF.AdwCustomizer
Cache hit for python3-anyascii, skipping build

(flatpak-builder:309): flatpak-builder-WARNING **: 20:57:55.692: Failed to get current git checksum: Failed to change to directory “/home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder/git/https_gitlab.gnome.org_jwestman_blueprint-compiler” (No such file or directory)
Cache miss, checking out last cache hit

(flatpak-builder:309): flatpak-builder-WARNING **: 20:57:55.706: rofiles-fuse not available, doing without
========================================================================
Building module blueprint-compiler in /home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder/build/blueprint-compiler-8
========================================================================
cp: cannot stat '/home/entityinarray/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder/git/https_gitlab.gnome.org_jwestman_blueprint-compiler': No such file or directory
Error: module blueprint-compiler: Child process exited with code 1
```

**Comment by EntityinArray** [comment]
Built with GNOME Builder, everything went fine, but upon launching it just exits.
![image](https://user-images.githubusercontent.com/18554021/183135596-4aab57fa-b3d1-455c-83ac-c695b6f7a355.png)

**Comment by ArtyIF** [comment]
Right, that looks like an issue with pygobject. Nothing I can do, unfortunately. It works fine on Fedora 36, which is what I'm using.

**Comment by EntityinArray** [comment]
Created an issue:
https://gitlab.gnome.org/GNOME/pygobject/-/issues/538

**Comment by ArtyIF** [comment]
I never ran the app like that. Try just using `flatpak run com.github.ArtyIF.AdwCustomizer`.

**Comment by daudix-UFO** [comment]
> I never ran the app like that. Try just using `flatpak run com.github.ArtyIF.AdwCustomizer`.

`com.github.GradienceTeam.Gradience`

Also, this issue is fixed :D
